FROM codequest/grpc-ruby:latest

# Set up proto directory and copy the code there:
ENV PROTO_HOME=/fortune-proto
RUN mkdir $PROTO_HOME
ADD ./proto $PROTO_HOME

# Set up library directory and generate protos:
ENV LIB_HOME=/fortune-lib
RUN mkdir $LIB_HOME
RUN protoc -I $PROTO_HOME \
              --ruby_out=$LIB_HOME \
              --grpc_out=$LIB_HOME \
              --plugin=protoc-gen-grpc=`which grpc_ruby_plugin` \
              $PROTO_HOME/fortune.proto

# Set up app directory:
ENV APP_HOME=/fortune-client
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# Add a Gemfile before the rest of the code, for caching purposes:
ADD ./client/Gemfile* $APP_HOME/
RUN bundle install --jobs 10

# Add the rest of the client code:
ADD ./client $APP_HOME

# Clean up installation artifacts:
RUN rm -rf $GRPC_PATH

WORKDIR $APP_HOME
